### ISSUE TITLE
[BUG] Login dont work with compose

### ISSUE THREAD

**Issue by Svenum** [iglu-sh/controller#12]
```yml
services:
  controller:
    image: ghcr.io/iglu-sh/iglu-controller-docker:latest
    environment:
      DATABASE_URL: postgresql://iglu:secret_password@postgres:5432/cache
      NEXT_PUBLIC_URL: http://localhost:3001
      NEXT_PUBLIC_CACHE_URL: http://localhost:3000
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - cache
  cache:
    image: ghcr.io/iglu-sh/iglu-cache-docker:latest
    environment:
      CACHE_ROOT_DOMAIN: http://localhost:3000
      CACHE_MAX_GB: 100
      LOG_LEVEL: INFO
      POSTGRES_USER: iglu
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: cache
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      CACHE_FILESYSTEM_DIR: /tmp/cache #Should be mounted to an outside container if you want to persist files, else set to something in the container
    volumes:
      - ./cache/nar_files:/tmp/cache
    ports:
      - 3000:3000
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: iglu
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: cache
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
```

```bash
[cache]      | error: Client has already been connected. You cannot reuse a client.
[cache]      |       at _connect (/nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/.bun/install/cache/pg@8.16.0@@@1/lib/client.js:95:19)
[cache]      |       at <anonymous> (/nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/.bun/install/cache/pg@8.16.0@@@1/lib/client.js:171:12)
[cache]      |       at new Promise (1:11)
[cache]      |       at connect (/nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/.bun/install/cache/pg@8.16.0@@@1/lib/client.js:170:12)
[cache]      |       at connect (/nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/utils/db.ts:31:31)
[cache]      |       at connect (/nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/utils/db.ts:28:27)
[cache]      |       at /nix/store/d0kn9xn05gqnnl3zdf24k3xqamyd44fw-iglu-cache-0.0.1/share/iglu-cache/index.ts:49:24
```
